theme: minima
lang:  pt-PT
show_downloads: no
title: Equipa de Usabilidade e Conteúdos
description: EUC / TICAPP / AMA I.P.
# If you want to link only specific pages in your header, uncomment this and add the path to the pages in
# order as they should show up.
#
header_pages: none 
